export enum SearchMode {
    ORGANIZATION = "ORGANIZATION",
    SECONDARY = "SECONDARY",
}

export enum Feature {
    PRODUCT = "PRODUCT",
    PRODUCT_STAGE = "PRODUCT_STAGE",
    COMPONENT = "COMPONENT",
    FACTORY = "FACTORY",
    FACTORY_STAGE = "FACTORY_STAGE",
    RESOURCE_ALLOCATION_PLAN = "RESOURCE_ALLOCATION_PLAN",
    FACTORY_INVENTORY_ITEM = "FACTORY_INVENTORY_ITEM",
    FACTORY_PRODUCTION_HISTORY = "FACTORY_PRODUCTION_HISTORY",
    FACTORY_PERFORMANCE = "FACTORY_PERFORMANCE",
    WAREHOUSE = "WAREHOUSE",
    WAREHOUSE_INVENTORY_ITEM = "WAREHOUSE_INVENTORY_ITEM",
    SUPPLIER = "SUPPLIER",
    SUPPLIER_ORDER = "SUPPLIER_ORDER",
    SUPPLIER_SHIPMENT = "SUPPLIER_SHIPMENT",
    SUPPLIER_PERFORMANCE = "SUPPLIER_PERFORMANCE",
    CLIENT = "CLIENT",
    CLIENT_ORDER = "CLIENT_ORDER",
    CLIENT_SHIPMENT = "CLIENT_SHIPMENT",
    CLIENT_EVALUATION = "CLIENT_EVALUATION",
}