export enum SearchMode {
    ORGANIZATION = "ORGANIZATION",
    SECONDARY = "SECONDARY",
}

export enum Feature {
    PRODUCT = "PRODUCT",
    FACTORY = "FACTORY",
    WAREHOUSE = "WAREHOUSE",
    SUPPLIER = "SUPPLIER",
    SUPPLIER_ORDER = "SUPPLIER_ORDER",
    SUPPLIER_SHIPMENT = "SUPPLIER_SHIPMENT",
    CLIENT = "CLIENT",
    CLIENT_ORDER = "CLIENT_ORDER",
    CLIENT_SHIPMENT = "CLIENT_SHIPMENT",
}