import { Injectable } from "@angular/core";
import { PlanTier, SubscriptionPlans } from "../models/SubscriptionPlan";

@Injectable({
    providedIn: 'root'
})
export class SubscriptionPlanService {

    private subscriptionPlans: SubscriptionPlans = {
        [PlanTier.NONE]: {
            dollarsPerMonth: 0,
            maxMembers: 2,
            maxRoles: 2,
            maxProducts: 1,
            realTimeNotificationsOn: false,
            emailNotificationsOn: false,
            customNotificationsOn: false,
            maxComponents: 1,
            maxProductStages: 1,
            maxFactories: 1,
            maxFactoryStages: 2,
            maxFactoryInventoryItems: 2,
            factoryPerformanceOn: false,
            maxWarehouses: 1,
            maxWarehouseInventoryItems: 2,
            maxSuppliers: 1,
            maxSupplierOrders: 2,
            maxSupplierShipments: 2,
            supplierPerformanceOn: false,
            maxClients: 1,
            maxClientOrders: 2,
            maxClientShipments: 2,
            clientEvaluationOn: false,
        },
        [PlanTier.BASIC]: {
            dollarsPerMonth: 30,
            maxMembers: 5,
            maxRoles: 5,
            maxProducts: 5,
            realTimeNotificationsOn: false,
            emailNotificationsOn: false,
            customNotificationsOn: false,
            maxComponents: 5,
            maxProductStages: 5,
            maxFactories: 5,
            maxFactoryStages: 20,
            maxFactoryInventoryItems: 20,
            factoryPerformanceOn: false,
            maxWarehouses: 5,
            maxWarehouseInventoryItems: 20,
            maxSuppliers: 5,
            maxSupplierOrders: 20,
            maxSupplierShipments: 20,
            supplierPerformanceOn: false,
            maxClients: 5,
            maxClientOrders: 20,
            maxClientShipments: 20,
            clientEvaluationOn: false,
        },
        [PlanTier.PROFESSIONAL]: {
            dollarsPerMonth: 120,
            maxMembers: 10,
            maxRoles: 20,
            maxProducts: 20,
            realTimeNotificationsOn: true,
            emailNotificationsOn: true,
            customNotificationsOn: false,
            maxComponents: 100,
            maxProductStages: 100,
            maxFactories: 100,
            maxFactoryStages: 2,
            maxFactoryInventoryItems: 2,
            factoryPerformanceOn: true,
            maxWarehouses: 100,
            maxWarehouseInventoryItems: 2,
            maxSuppliers: 100,
            maxSupplierOrders: 2,
            maxSupplierShipments: 2,
            supplierPerformanceOn: true,
            maxClients: 100,
            maxClientOrders: 2,
            maxClientShipments: 2,
            clientEvaluationOn: true,
        },
        [PlanTier.ENTERPRISE]: {
            dollarsPerMonth: 700,
            maxMembers: -1,
            maxRoles: -1,
            maxProducts: 1,
            realTimeNotificationsOn: true,
            emailNotificationsOn: true,
            customNotificationsOn: true,
            maxComponents: 1,
            maxProductStages: 1,
            maxFactories: 1,
            maxFactoryStages: -1,
            maxFactoryInventoryItems: -1,
            factoryPerformanceOn: true,
            maxWarehouses: 1,
            maxWarehouseInventoryItems: -1,
            maxSuppliers: 1,
            maxSupplierOrders: -1,
            maxSupplierShipments: -1,
            supplierPerformanceOn: true,
            maxClients: 1,
            maxClientOrders: 2,
            maxClientShipments: 2,
            clientEvaluationOn: true,
        }
    }

    getSubscriptionPlan(tier: PlanTier) {
        return this.subscriptionPlans[tier];
    }
}